### ISSUE TITLE
Insert images

### ISSUE THREAD

**Issue by jacopo-lupi** [BackgroundNose/EnergyLeveller#2] opened 2020-01-21 14:50 UTC
Dear developer,
I'm still an enthusiastic user of your script :D
It would be nice to have the possibility of inserting images of molecules at each node of the PES. Is that possible?

**Comment by JFurness1** [comment] 2020-01-26 22:32
Thank you for your use!

Sure, that's definitely possible. 

It will take me a little thinking to work out the best way to go it, so I'll take a few days to piece it together and commit an update. I'll let you know when it's ready. :)

**Comment by JFurness1** [comment] 2020-02-07 05:23
Sorry this has taken so long, I've had life commitments recently and haven't found the time to look at it. Tonight I added one way of including images into the plot.

The state blocks in the input file now take 3 new fields, as always, take a look at example.inp from this repo for details.

image = \<relative path to image\>
image offset = \<offset in x\>,\<offset in y\>
image scale = \<scale\>

Without offset the bottom left of the image will be placed at the left hand point of the state energy level, and scaled such that it has the same width as the energy level line. The offsets are in slightly strange units of "state width" for x (i.e. 1 will move it one state width to the right), while y is in energy. 

The "scale" option scales up or down from this default width. All of this scaling can introduce artifacts into the image, so it's best to use a high resolution image and scale it down.

There is a further option for annotating images onto the that I might implement as well. This would reduce the artifacts from the scaling, but is a little less convenient for specifying where they go. Including both options is probably best, but I hope this is helpful for now.

**Comment by JFurness1** [comment] 2020-08-12 02:53
I remember there was an outstanding issue with aspect ratios not working correctly, but I can't find any record of that issue now.

Is this still a problem?

**Comment by Shubh1906** [comment] 2020-11-20 14:46
Dear Developer,

I hope you are doing good, and safe!

I am new in programming and learning python. I am trying to plot the energy levels using your script. I have my own input file, in which I have energies (in the negative) with degeneracy. But giving me errors upon running. Can you help me with this, please!?

**Comment by JFurness1** [comment] 2020-11-20 15:28
Sure thing. I'll take a look at what's going wrong. 

I see you emailed me an example of the problematic input separately.

I'll take a look now and see what I can find, I imagine it will be an easy fix.

James

**Comment by JFurness1** [comment] 2020-11-20 16:03
Ok, So I think the problem is with your input rather than the script.
There are two problems you need to fix.

The first is that you have lines like 

`name        = reactants text-colour = black`

which accidentally combine the `name` and `text-colour` fields on one line. This should be broken into

```
name = reactants
text-colour = black
```

Secondly, all of your states are given the same name "reactants". The program needs each state to have a different name so it can identify them for cross linking (internally it stores them as a dictionary). You can fix this by giving each state a useful name, or by simply adding an incrementing number after reactants.

```
{
name = reactants1
energy      = 0.0
column = 1
}
{
name = reactants2
energy = -4.7657039
column = 2
}
# and so on
```

Fixing these input problem and the program runs well.

**Comment by JFurness1** [comment] 2020-11-20 16:03
I also tracked down the aspect ratio bug that was reported before. That should be fixed in the current version.

**Closed as completed by JFurness1** 2020-11-20 16:03 UTC
